// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header"; // Import the Header component
// import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Desknet",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header /> Render the Header component here */}
        {children}
        {/* <Footer /> Render the Footer component here */}
      </body>
    </html>
  );
}